name: Permission check
on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
      - 'root/migrations/*'

jobs:
  permission_check:
    if: github.repository != NujSuper/docker-openssh-server
    uses: linuxserver/github-workflows/.github/workflows/init-svc-executable-permissions.yml@v1
